### ISSUE TITLE
Moving away from keyed audit logs

### ISSUE THREAD

**Issue by chanlawrencet** [JumboCode/South-Florida-Jewish-Academy#157]
Now we have numbers, but numbers are hard to keep track of on the front end. Proposal to change to strings for frontend to more easily display the action?

**Comment by jhuang09** [comment]
@chanlawrencet Would you like something like:
```
"reset"                 : 0,
```
to become 
```
"reset"                 : "reset database",
```

**Comment by chanlawrencet** [comment]
yeah or that the decorations can go straight into the database without the need for the table
`usersDOM.addAction(user_info['nickname'], datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"), action)`

**Comment by chanlawrencet** [comment]
This way we can just use the string

**Comment by jhuang09** [comment]
Gotcha! Will work on that. Thanks!

**Comment by chanlawrencet** [comment]
Great! Let me know if you have any more questions

**Comment by jhuang09** [comment]
Might change some of the strings for the `action` so that it's more readable (and doesn't have underscores littered all over)

**Comment by jhuang09** [comment]
Would it be a good idea to remove `database/assets/audit_mapper.py` or should we still keep it for now?

**Comment by chanlawrencet** [comment]
This looks good! And yeah we can remove `audit_mapper`

**Comment by chanlawrencet** [comment]
Done with #162
