### ISSUE TITLE
Non-admin editing

### ISSUE THREAD

**Issue by chanlawrencet** [JumboCode/South-Florida-Jewish-Academy#226]
Disable non-admin editing of forms in the student profile

**Comment by jchin01** [comment]
can you point me in the right direction on how to check the role of the user so that I can use that to disable switch that is used to allow editing

**Comment by chanlawrencet** [comment]
There's a isAuthorized function in run.py somewhere -- send the result of that over the fetch and allow the person to edit it if it's true. Let me know if you want a bit more guidance!
